"""initial

Revision ID: 4ab2bfa0f392
Revises: 
Create Date: 2025-03-21 17:33:41.147333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab2bfa0f392'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                    sa.Column('username', sa.String(255), unique=True, nullable=False),
                    sa.Column('password', sa.String(255), nullable=False),
                    sa.Column('email', sa.String(255), unique=True, nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
